# If KERNELRELEASE is defined, we've been invoked from the kernel build system
# and can use its language.
ifneq ($(KERNELRELEASE),)
	obj-m += ledfloor.o

# Otherwise, we were called directly from the command line. Invoke the kernel
# build system.
else
	KERNELDIR ?= /lib/modules/$(shell uname -r)/build
	PWD := $(shell pwd)

KBUILD_TARGETS	:= clean help modules modules_install

.PHONY: all $(KBUILD_TARGETS)
all: modules

$(KBUILD_TARGETS):
	$(MAKE) -C $(KERNELDIR) M=$(PWD) $@

endif
