.PHONY : all clean

all:
	$(MAKE) -C lfdemo all
	$(MAKE) -C lfserver all
	$(MAKE) -C lfshow all
	$(MAKE) -C recode all

clean:
	$(MAKE) -C lfdemo clean
	$(MAKE) -C lfserver clean
	$(MAKE) -C lfshow clean
	$(MAKE) -C recode clean
